set
search_path to core;
INSERT INTO security.users (internal_id,
                            tenant_id,
                            user_type,
                            username,
                            country_id,
                            phone_country_id,
                            phone,
                            phone_verified,
                            phone_verified_at,
                            email,
                            email_verified,
                            email_verified_at,
                            password_hash,
                            last_login_at,
                            status,
                            created_at,
                            updated_at,
                            created_by,
                            updated_by,
                            version)
VALUES ('USR-ADM-001',
        NULL, -- PLATFORM_ADMIN → tenant_id must be NULL
        'PLATFORM_ADMIN',
        'prakjm',
        (SELECT id FROM core.countries WHERE country_code2 = 'IN'),
        (SELECT id FROM core.country_calling_codes WHERE calling_code = '+91'),
        '+919876543210',
        FALSE,
        NULL,
        'prakjm@gmail.com',
        TRUE, -- admin email pre-verified
        NOW(),
        '$2a$12$2yOChyhSuJm/naTBUjGZb.6d6mu1NsXS8XWRFousQfRTwzy0ZQtWW', -- bcrypt hash, change password after first login
        NULL,
        'A',
        NOW(),
        NOW(),
        NULL, -- no created_by for seed records
        NULL,
        1),
       ('USR-ADM-002',
        NULL,
        'PLATFORM_ADMIN',
        'mahesh',
        (SELECT id FROM core.countries WHERE country_code2 = 'IN'),
        (SELECT id FROM core.country_calling_codes WHERE calling_code = '+91'),
        '+917654321098',
        FALSE,
        NULL,
        'mahesh@gmail.com',
        TRUE,
        NOW(),
        '$2a$12$2yOChyhSuJm/naTBUjGZb.6d6mu1NsXS8XWRFousQfRTwzy0ZQtWW',
        NULL,
        'A',
        NOW(),
        NOW(),
        NULL,
        NULL,
        1);